### ISSUE TITLE
issue about corners_pad[:len(corners)] = corners

### ISSUE THREAD

**Issue by Martin-1999** [ywyue/RoomFormer#18]
I got this problem when training on my own dataset

![1701153750936](https://github.com/ywyue/RoomFormer/assets/52899461/121e87a8-b328-42a1-aa1b-c06dbccd0c92)
It looks like the length of the corners is 298, but the length of the corners_pad is only 80
Is this caused by my training data?
be like: 
![image](https://github.com/ywyue/RoomFormer/assets/52899461/9496e447-f91c-4e0c-a518-9ac6906d2c9b)

thank you very much!

**Comment by ywyue** [comment]
Thanks for your interest in our work. We assume the maximum number of vertices for each polygon is 40 - that's why the length of the `corners_pad ` [(x1,y1), (x2,y2), ... ] is only 80 (40×2). It seems that your dataset contains a polygon with 298/2=149 vertices. So I suggest that you check the **maximum number of polygons (M)** and **maximum number of vertices per polygon (N)** in your dataset and set the following two parameters accordingly:

```
--num_queries=M×N \
--num_polys=M \
```

Hope it helps :)

**Comment by Martin-1999** [comment]
Thanks!

**Comment by Martin-1999** [comment]
Thanks!
